spring:
  application:
    name: NewsManagementSystem222
  ai:
    model:
      chat: google-genai
    google:
      genai:
        api-key: "${GEMINI_API_KEY}"
        chat:
          model: "${GEMINI_MODEL:gemini-2.5-flash}"

        embedding:
          api-key: ${GEMINI_API_KEY}
          text:
            model: gemini-embedding-2
            dimensions: 768
            auto-truncate: true
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        collection-name: news_documents
        use-tls: false
        initialize-schema: true
    mcp:
      client:
        type: SYNC
        stdio:
          servers-configuration: classpath:servers.json
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/NewsManagementSystem}
    username: "root"
    password: "1234"
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${GOOGLE_CLIENT_ID}"
            client-secret: "${GOOGLE_CLIENT_SECRET}"
            scope:
              - openid
              - profile
              - email
          github:
            client-id: "${GITHUB_CLIENT_ID}"
            client-secret: "${GITHUB_CLIENT_SECRET}"
            scope:
              - user
              - email
        provider:
          google:
          github:
#            user-name-attribute: login
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: always
  tracing:
    export:
      otlp:
        enabled: "${OTLP_TRACING_ENABLED:false}"
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        enabled: "${OTLP_METRICS_ENABLED:false}"
        url: "${OTLP_METRICS_URL:http://localhost:4318/v1/metrics}"
  opentelemetry:
    tracing:
      export:
        otlp:
          transport: http
          endpoint: "${OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}"
    resource-attributes:
      "service.name": "${spring.application.name}"

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  include-application-name: false
  level:
    org:
      springframework:
        security=DEBUG:

jdbc:
  datasource-proxy:
    enabled: true
    include-parameter-values: false
  opentelemetry:
    enabled: true
    spans:
      enabled: true
  includes:
    - QUERY

#sample
app:
  sample-message: This value was loaded from application.yml with @Value
  news:
    title: News Management System
    page-size: 10

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    csrf:
      enabled=true:






